# fly.toml app configuration file generated for kissmychat-form on 2024-05-18T20:39:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kissmychat-form'
primary_region = 'waw'
swap_size_mb = 512


[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256MB'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  handlers = ["tls", "http"]
  port = 443
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "3000s"
  method = "GET"
  timeout = "5s"
  path = "/"